"""ORM model for the Certifications domain.

Represents a single certification record in the ``certifications`` table.
Each certification has metadata (name, issuer, date, credential URL, badge
image) plus a ``content_embedding`` vector column used by the RAG search
pipeline for semantic similarity queries via pgvector.

Example::

    cert = Certification(
        name="AWS Certified Solutions Architect, Associate",
        issuer="Amazon Web Services",
        issued_at=date(2024, 6, 15),
        credential_url="https://aws.amazon.com/verification/...",
        badge_image_url="https://images.credly.com/...",
    )
    db.add(cert)
    await db.commit()
"""

from datetime import date

from pgvector.sqlalchemy import Vector
from sqlalchemy import Boolean, Date, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.core.constants import EMBEDDING_DIMENSIONS
from app.db.base import Base, TimestampMixin, UUIDMixin


class Certification(Base, UUIDMixin, TimestampMixin):
    """SQLAlchemy ORM model representing a professional certification.

    Inherits a UUID primary key from :class:`~app.db.base.UUIDMixin` and
    ``created_at`` / ``updated_at`` audit columns from
    :class:`~app.db.base.TimestampMixin`.

    The ``content_embedding`` column stores a pgvector
    ``vector(EMBEDDING_DIMENSIONS)`` value generated by the RAG service from
    the certification's name, issuer, and description.  It is ``NULL`` until
    the embedding pipeline runs for the first time.

    Attributes:
        name: Full name of the certification
            (e.g. ``"AWS Certified Solutions Architect, Associate"``).
        issuer: Organisation that issued the certification
            (e.g. ``"Amazon Web Services"``).
        description: Optional plain-text description of what the
            certification covers.  Shown on the detail view and used to
            enrich the RAG embedding.
        issued_at: Date the certification was awarded.
        expires_at: Optional expiry date.  ``None`` for certifications
            that do not expire.
        credential_id: Optional alphanumeric credential / verification ID
            assigned by the issuer.
        credential_url: Optional URL to the issuer's verification page.
        badge_image_url: Optional URL of the certification badge image
            (e.g. a Credly badge PNG/SVG).
        featured: When ``True`` the certification appears in the homepage
            highlights or featured certifications section.
        content_embedding: pgvector embedding of the certification's
            textual content, used for semantic search.  ``None`` until
            the RAG service has processed the record.
    """

    __tablename__ = "certifications"

    name: Mapped[str] = mapped_column(String(255), nullable=False)
    issuer: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    issued_at: Mapped[date] = mapped_column(Date, nullable=False)
    expires_at: Mapped[date | None] = mapped_column(Date, nullable=True)
    credential_id: Mapped[str | None] = mapped_column(String(255))
    credential_url: Mapped[str | None] = mapped_column(String(500))
    badge_image_url: Mapped[str | None] = mapped_column(String(500))
    featured: Mapped[bool] = mapped_column(Boolean, default=False)
    content_embedding: Mapped[list[float] | None] = mapped_column(
        Vector(EMBEDDING_DIMENSIONS), nullable=True
    )
