"""ORM model for the Posts / Blog domain.

Represents a single blog post entry in the ``posts`` table.  Each post has
rich metadata (title, slug, tags, published state) plus a ``content_embedding``
vector column used by the RAG search pipeline for semantic similarity queries
via pgvector.

Example::

    post = Post(
        title="Building a RAG Pipeline with FastAPI",
        slug="building-rag-pipeline-fastapi",
        excerpt="A walkthrough of building a production RAG pipeline...",
        body="## Introduction\\n\\nRAG stands for...",
        tags=["ai", "fastapi", "python"],
        published=True,
    )
    db.add(post)
    await db.commit()
"""

from pgvector.sqlalchemy import Vector
from sqlalchemy import ARRAY, Boolean, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.core.constants import EMBEDDING_DIMENSIONS
from app.db.base import Base, TimestampMixin, UUIDMixin


class Post(Base, UUIDMixin, TimestampMixin):
    """SQLAlchemy ORM model representing a blog post.

    Inherits a UUID primary key from :class:`~app.db.base.UUIDMixin` and
    ``created_at`` / ``updated_at`` audit columns from
    :class:`~app.db.base.TimestampMixin`.

    The ``content_embedding`` column stores a pgvector
    ``vector(EMBEDDING_DIMENSIONS)`` value generated by the RAG service from
    the post's title, excerpt, and body.  It is ``NULL`` until the embedding
    pipeline runs for the first time.

    Attributes:
        title: Display title of the post (max 255 chars).
        slug: URL-safe unique identifier derived from the title
            (e.g. ``"building-rag-pipeline-fastapi"``).  Indexed and unique.
        excerpt: Short plain-text summary shown in post cards and list views.
        body: Full rich-text body of the post (TipTap JSON or Markdown).
            ``None`` for draft posts that have not yet had content added.
        tags: Free-form string labels used for filtering and display
            (e.g. ``["ai", "python", "tutorial"]``).
        cover_image_url: URL of the post's cover image (optional).
        published: When ``False`` the post is hidden from public API
            responses (draft mode).
        reading_time_minutes: Estimated reading time in minutes.
            Displayed in the post card and header.  ``None`` until computed.
        content_embedding: pgvector embedding of the post's textual content,
            used for semantic search.  ``None`` until the RAG service has
            processed the post.
    """

    __tablename__ = "posts"

    title: Mapped[str] = mapped_column(String(255), nullable=False)
    slug: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    excerpt: Mapped[str] = mapped_column(Text, nullable=False)
    body: Mapped[str | None] = mapped_column(Text)
    tags: Mapped[list[str]] = mapped_column(ARRAY(String), default=list)
    cover_image_url: Mapped[str | None] = mapped_column(String(500))
    published: Mapped[bool] = mapped_column(Boolean, default=False)
    reading_time_minutes: Mapped[int | None] = mapped_column(nullable=True)
    content_embedding: Mapped[list[float] | None] = mapped_column(
        Vector(EMBEDDING_DIMENSIONS), nullable=True
    )
