"""ORM model for the Projects domain.

Represents a single portfolio project entry in the ``projects`` table.
Each project has rich metadata (title, slug, tech stack, tags, URLs) plus
an optional ``content_embedding`` vector column used by the RAG search
pipeline to perform semantic similarity queries via pgvector.

Example::

    project = Project(
        title="My Project",
        slug="my-project",
        description="A short description.",
        tags=["python", "fastapi"],
        tech_stack=["Python", "FastAPI", "PostgreSQL"],
        published=True,
    )
    db.add(project)
    await db.commit()
"""

from pgvector.sqlalchemy import Vector
from sqlalchemy import ARRAY, Boolean, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.core.constants import EMBEDDING_DIMENSIONS
from app.db.base import Base, TimestampMixin, UUIDMixin


class Project(Base, UUIDMixin, TimestampMixin):
    """SQLAlchemy ORM model representing a portfolio project.

    Inherits a UUID primary key from :class:`~app.db.base.UUIDMixin` and
    ``created_at`` / ``updated_at`` audit columns from
    :class:`~app.db.base.TimestampMixin`.

    The ``content_embedding`` column stores a pgvector
    ``vector(EMBEDDING_DIMENSIONS)`` value generated by the RAG service from
    the project's title, description, and content.  It is ``NULL`` until the
    embedding pipeline runs for the first time.

    Attributes:
        title: Display name of the project (max 255 chars).
        slug: URL-safe unique identifier derived from the title
            (e.g. ``"my-portfolio-site"``).  Indexed and unique.
        description: Short plain-text summary shown in project cards.
        content: Optional rich-text body (TipTap JSON or Markdown).
        tags: Free-form string labels used for filtering
            (e.g. ``["ai", "open-source"]``).
        tech_stack: Technologies used, shown as pill badges
            (e.g. ``["Python", "FastAPI", "React"]``).
        live_url: Link to the deployed project (optional).
        repo_url: Link to the source repository (optional).
        image_url: URL of the project's cover image (optional).
        featured: When ``True`` the project appears on the homepage
            featured section.
        published: When ``False`` the project is hidden from public API
            responses (draft mode).
        order: Integer sort weight — lower values appear first.
        content_embedding: pgvector embedding of the project's textual
            content, used for semantic search.  ``None`` until the RAG
            service has processed the project.
    """

    __tablename__ = "projects"

    title: Mapped[str] = mapped_column(String(255), nullable=False)
    slug: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    content: Mapped[str | None] = mapped_column(Text)
    tags: Mapped[list[str]] = mapped_column(ARRAY(String), default=list)
    tech_stack: Mapped[list[str]] = mapped_column(ARRAY(String), default=list)
    live_url: Mapped[str | None] = mapped_column(String(500))
    repo_url: Mapped[str | None] = mapped_column(String(500))
    image_url: Mapped[str | None] = mapped_column(String(500))
    featured: Mapped[bool] = mapped_column(Boolean, default=False)
    published: Mapped[bool] = mapped_column(Boolean, default=False)
    order: Mapped[int] = mapped_column(default=0)
    content_embedding: Mapped[list[float] | None] = mapped_column(
        Vector(EMBEDDING_DIMENSIONS), nullable=True
    )
