// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AiWriteApiV1AiWritePostData, AiWriteApiV1AiWritePostErrors, AiWriteApiV1AiWritePostResponses, CreateProjectApiV1ProjectsPostData, CreateProjectApiV1ProjectsPostErrors, CreateProjectApiV1ProjectsPostResponses, DeleteProjectApiV1ProjectsSlugDeleteData, DeleteProjectApiV1ProjectsSlugDeleteErrors, DeleteProjectApiV1ProjectsSlugDeleteResponses, GetFeaturedProjectsApiV1ProjectsFeaturedGetData, GetFeaturedProjectsApiV1ProjectsFeaturedGetResponses, GetProjectApiV1ProjectsSlugGetData, GetProjectApiV1ProjectsSlugGetErrors, GetProjectApiV1ProjectsSlugGetResponses, GetProjectsApiV1ProjectsGetData, GetProjectsApiV1ProjectsGetErrors, GetProjectsApiV1ProjectsGetResponses, HealthHealthGetData, HealthHealthGetResponses, LoginApiV1AuthLoginPostData, LoginApiV1AuthLoginPostErrors, LoginApiV1AuthLoginPostResponses, LogoutApiV1AuthLogoutPostData, LogoutApiV1AuthLogoutPostErrors, LogoutApiV1AuthLogoutPostResponses, MeApiV1AuthMeGetData, MeApiV1AuthMeGetErrors, MeApiV1AuthMeGetResponses, UpdateProjectApiV1ProjectsSlugPatchData, UpdateProjectApiV1ProjectsSlugPatchErrors, UpdateProjectApiV1ProjectsSlugPatchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Projects
 */
export const getProjectsApiV1ProjectsGet = <ThrowOnError extends boolean = false>(options?: Options<GetProjectsApiV1ProjectsGetData, ThrowOnError>) => (options?.client ?? client).get<GetProjectsApiV1ProjectsGetResponses, GetProjectsApiV1ProjectsGetErrors, ThrowOnError>({ url: '/api/v1/projects/', ...options });

/**
 * Create Project
 */
export const createProjectApiV1ProjectsPost = <ThrowOnError extends boolean = false>(options: Options<CreateProjectApiV1ProjectsPostData, ThrowOnError>) => (options.client ?? client).post<CreateProjectApiV1ProjectsPostResponses, CreateProjectApiV1ProjectsPostErrors, ThrowOnError>({
    url: '/api/v1/projects/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Featured Projects
 */
export const getFeaturedProjectsApiV1ProjectsFeaturedGet = <ThrowOnError extends boolean = false>(options?: Options<GetFeaturedProjectsApiV1ProjectsFeaturedGetData, ThrowOnError>) => (options?.client ?? client).get<GetFeaturedProjectsApiV1ProjectsFeaturedGetResponses, unknown, ThrowOnError>({ url: '/api/v1/projects/featured', ...options });

/**
 * Delete Project
 */
export const deleteProjectApiV1ProjectsSlugDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteProjectApiV1ProjectsSlugDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteProjectApiV1ProjectsSlugDeleteResponses, DeleteProjectApiV1ProjectsSlugDeleteErrors, ThrowOnError>({ url: '/api/v1/projects/{slug}', ...options });

/**
 * Get Project
 */
export const getProjectApiV1ProjectsSlugGet = <ThrowOnError extends boolean = false>(options: Options<GetProjectApiV1ProjectsSlugGetData, ThrowOnError>) => (options.client ?? client).get<GetProjectApiV1ProjectsSlugGetResponses, GetProjectApiV1ProjectsSlugGetErrors, ThrowOnError>({ url: '/api/v1/projects/{slug}', ...options });

/**
 * Update Project
 */
export const updateProjectApiV1ProjectsSlugPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateProjectApiV1ProjectsSlugPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateProjectApiV1ProjectsSlugPatchResponses, UpdateProjectApiV1ProjectsSlugPatchErrors, ThrowOnError>({
    url: '/api/v1/projects/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Ai Write
 */
export const aiWriteApiV1AiWritePost = <ThrowOnError extends boolean = false>(options: Options<AiWriteApiV1AiWritePostData, ThrowOnError>) => (options.client ?? client).post<AiWriteApiV1AiWritePostResponses, AiWriteApiV1AiWritePostErrors, ThrowOnError>({
    url: '/api/v1/ai/write',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Authenticate and receive a JWT access token
 *
 * Authenticate with email + password.
 *
 * On success the JWT access token is:
 *
 * 1. Set as an httpOnly cookie (``access_token``) — used by the browser frontend.
 * 2. Returned in the response body — used by API clients, tests, and the
 * OpenAPI ``/docs`` UI.
 *
 * Args:
 * data: Login credentials — ``email`` and ``password``.
 * response: FastAPI response object used to set the cookie.
 * db: Active async database session.
 * auth_service: Injected auth service.
 *
 * Returns:
 * :class:`~app.schemas.auth.TokenResponse` containing the raw JWT and
 * token type (``"bearer"``).
 *
 * Raises:
 * HTTPException: HTTP 401 when the email is not found or the password
 * is incorrect.  The error message is deliberately vague to avoid
 * leaking whether the email exists.
 * HTTPException: HTTP 403 when the account has been deactivated.
 *
 * Example::
 *
 * POST /api/v1/auth/login
 * Content-Type: application/json
 *
 * {"email": "luc@example.com", "password": "supersecret"}
 *
 * → 200 OK
 * Set-Cookie: access_token=<JWT>; HttpOnly; SameSite=Lax; Path=/
 * {"access_token": "<JWT>", "token_type": "bearer"}
 */
export const loginApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiV1AuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<LoginApiV1AuthLoginPostResponses, LoginApiV1AuthLoginPostErrors, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Return the currently authenticated user
 *
 * Return the profile of the currently authenticated user.
 *
 * This endpoint is used by the frontend on app load to determine whether a
 * valid session cookie exists and to populate the auth context.  It also
 * serves as a liveness check for the auth system.
 *
 * Args:
 * current_user: Resolved from the ``get_current_user`` dependency —
 * reads the ``access_token`` cookie or the ``Authorization`` header.
 *
 * Returns:
 * The :class:`~app.schemas.auth.UserResponse` for the authenticated user.
 * The ``hashed_password`` field is never included in this response.
 *
 * Raises:
 * HTTPException: HTTP 401 when no valid token is present.
 * HTTPException: HTTP 403 when the account is inactive.
 *
 * Example::
 *
 * GET /api/v1/auth/me
 * Cookie: access_token=<JWT>
 *
 * → 200 OK
 * {
 * "id": "...",
 * "email": "luc@example.com",
 * "is_active": true,
 * "is_superuser": true,
 * "created_at": "...",
 * "updated_at": "..."
 * }
 */
export const meApiV1AuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<MeApiV1AuthMeGetData, ThrowOnError>) => (options?.client ?? client).get<MeApiV1AuthMeGetResponses, MeApiV1AuthMeGetErrors, ThrowOnError>({ url: '/api/v1/auth/me', ...options });

/**
 * Invalidate the current session
 *
 * Log out the currently authenticated user.
 *
 * Clears the ``access_token`` httpOnly cookie so the browser stops sending
 * it on subsequent requests.
 *
 * JWT tokens are stateless — there is no server-side session to invalidate.
 * The token technically remains valid until its ``exp`` claim is reached.
 * For the portfolio's use case (single owner, long-lived sessions) this is
 * an acceptable trade-off.  If token revocation becomes a requirement,
 * introduce a Redis-backed blocklist and check it in
 * :func:`~app.core.deps.get_current_user`.
 *
 * Args:
 * response: FastAPI response object used to delete the cookie.
 * _: The authenticated user — required only to enforce that an active
 * session exists before clearing it.  The value is intentionally
 * discarded.
 *
 * Returns:
 * ``None`` — HTTP 204 No Content.
 *
 * Raises:
 * HTTPException: HTTP 401 when no valid token is present.
 *
 * Example::
 *
 * POST /api/v1/auth/logout
 * Cookie: access_token=<JWT>
 *
 * → 204 No Content
 * Set-Cookie: access_token=; Max-Age=0; Path=/
 */
export const logoutApiV1AuthLogoutPost = <ThrowOnError extends boolean = false>(options?: Options<LogoutApiV1AuthLogoutPostData, ThrowOnError>) => (options?.client ?? client).post<LogoutApiV1AuthLogoutPostResponses, LogoutApiV1AuthLogoutPostErrors, ThrowOnError>({ url: '/api/v1/auth/logout', ...options });

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
