// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Tech Stack
     */
    tech_stack?: Array<string>;
    /**
     * Live Url
     */
    live_url?: string | null;
    /**
     * Repo Url
     */
    repo_url?: string | null;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Featured
     */
    featured?: boolean;
    /**
     * Published
     */
    published?: boolean;
    /**
     * Order
     */
    order?: number;
    /**
     * Slug
     */
    slug?: string | null;
};

/**
 * ProjectResponse
 */
export type ProjectResponse = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Tech Stack
     */
    tech_stack?: Array<string>;
    /**
     * Live Url
     */
    live_url?: string | null;
    /**
     * Repo Url
     */
    repo_url?: string | null;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Featured
     */
    featured?: boolean;
    /**
     * Published
     */
    published?: boolean;
    /**
     * Order
     */
    order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Tech Stack
     */
    tech_stack?: Array<string> | null;
    /**
     * Live Url
     */
    live_url?: string | null;
    /**
     * Repo Url
     */
    repo_url?: string | null;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Featured
     */
    featured?: boolean | null;
    /**
     * Published
     */
    published?: boolean | null;
    /**
     * Order
     */
    order?: number | null;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WriteMode
 */
export type WriteMode = 'write' | 'improve' | 'summarise';

/**
 * WriteRequest
 */
export type WriteRequest = {
    /**
     * Prompt
     */
    prompt: string;
    mode: WriteMode;
    /**
     * Context
     */
    context?: string | null;
};

export type GetProjectsApiV1ProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Published Only
         */
        published_only?: boolean;
    };
    url: '/api/v1/projects/';
};

export type GetProjectsApiV1ProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectsApiV1ProjectsGetError = GetProjectsApiV1ProjectsGetErrors[keyof GetProjectsApiV1ProjectsGetErrors];

export type GetProjectsApiV1ProjectsGetResponses = {
    /**
     * Response Get Projects Api V1 Projects  Get
     *
     * Successful Response
     */
    200: Array<ProjectResponse>;
};

export type GetProjectsApiV1ProjectsGetResponse = GetProjectsApiV1ProjectsGetResponses[keyof GetProjectsApiV1ProjectsGetResponses];

export type CreateProjectApiV1ProjectsPostData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/projects/';
};

export type CreateProjectApiV1ProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectApiV1ProjectsPostError = CreateProjectApiV1ProjectsPostErrors[keyof CreateProjectApiV1ProjectsPostErrors];

export type CreateProjectApiV1ProjectsPostResponses = {
    /**
     * Successful Response
     */
    201: ProjectResponse;
};

export type CreateProjectApiV1ProjectsPostResponse = CreateProjectApiV1ProjectsPostResponses[keyof CreateProjectApiV1ProjectsPostResponses];

export type GetFeaturedProjectsApiV1ProjectsFeaturedGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/projects/featured';
};

export type GetFeaturedProjectsApiV1ProjectsFeaturedGetResponses = {
    /**
     * Response Get Featured Projects Api V1 Projects Featured Get
     *
     * Successful Response
     */
    200: Array<ProjectResponse>;
};

export type GetFeaturedProjectsApiV1ProjectsFeaturedGetResponse = GetFeaturedProjectsApiV1ProjectsFeaturedGetResponses[keyof GetFeaturedProjectsApiV1ProjectsFeaturedGetResponses];

export type DeleteProjectApiV1ProjectsSlugDeleteData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}';
};

export type DeleteProjectApiV1ProjectsSlugDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectApiV1ProjectsSlugDeleteError = DeleteProjectApiV1ProjectsSlugDeleteErrors[keyof DeleteProjectApiV1ProjectsSlugDeleteErrors];

export type DeleteProjectApiV1ProjectsSlugDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectApiV1ProjectsSlugDeleteResponse = DeleteProjectApiV1ProjectsSlugDeleteResponses[keyof DeleteProjectApiV1ProjectsSlugDeleteResponses];

export type GetProjectApiV1ProjectsSlugGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}';
};

export type GetProjectApiV1ProjectsSlugGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectApiV1ProjectsSlugGetError = GetProjectApiV1ProjectsSlugGetErrors[keyof GetProjectApiV1ProjectsSlugGetErrors];

export type GetProjectApiV1ProjectsSlugGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type GetProjectApiV1ProjectsSlugGetResponse = GetProjectApiV1ProjectsSlugGetResponses[keyof GetProjectApiV1ProjectsSlugGetResponses];

export type UpdateProjectApiV1ProjectsSlugPatchData = {
    body: ProjectUpdate;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}';
};

export type UpdateProjectApiV1ProjectsSlugPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectApiV1ProjectsSlugPatchError = UpdateProjectApiV1ProjectsSlugPatchErrors[keyof UpdateProjectApiV1ProjectsSlugPatchErrors];

export type UpdateProjectApiV1ProjectsSlugPatchResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type UpdateProjectApiV1ProjectsSlugPatchResponse = UpdateProjectApiV1ProjectsSlugPatchResponses[keyof UpdateProjectApiV1ProjectsSlugPatchResponses];

export type AiWriteApiV1AiWritePostData = {
    body: WriteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/write';
};

export type AiWriteApiV1AiWritePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiWriteApiV1AiWritePostError = AiWriteApiV1AiWritePostErrors[keyof AiWriteApiV1AiWritePostErrors];

export type AiWriteApiV1AiWritePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginApiV1AuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type MeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type MeApiV1AuthMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeApiV1AuthMeGetError = MeApiV1AuthMeGetErrors[keyof MeApiV1AuthMeGetErrors];

export type MeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type MeApiV1AuthMeGetResponse = MeApiV1AuthMeGetResponses[keyof MeApiV1AuthMeGetResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutApiV1AuthLogoutPostError = LogoutApiV1AuthLogoutPostErrors[keyof LogoutApiV1AuthLogoutPostErrors];

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiV1AuthLogoutPostResponse = LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];
