// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * CertificationCreate
 *
 * Schema for creating a new certification record.
 */
export type CertificationCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Issuer
     */
    issuer: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Issued At
     */
    issued_at: string;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Credential Id
     */
    credential_id?: string | null;
    /**
     * Credential Url
     */
    credential_url?: string | null;
    /**
     * Badge Image Url
     */
    badge_image_url?: string | null;
    /**
     * Featured
     */
    featured?: boolean;
};

/**
 * CertificationResponse
 *
 * Schema for returning a certification in API responses.
 *
 * Includes database-generated fields like ``id`` and timestamps.
 */
export type CertificationResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Issuer
     */
    issuer: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Issued At
     */
    issued_at: string;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Credential Id
     */
    credential_id?: string | null;
    /**
     * Credential Url
     */
    credential_url?: string | null;
    /**
     * Badge Image Url
     */
    badge_image_url?: string | null;
    /**
     * Featured
     */
    featured?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CertificationUpdate
 *
 * Schema for updating an existing certification record.
 *
 * All fields are optional. Only provided fields will be updated.
 */
export type CertificationUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Issuer
     */
    issuer?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Issued At
     */
    issued_at?: string | null;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Credential Id
     */
    credential_id?: string | null;
    /**
     * Credential Url
     */
    credential_url?: string | null;
    /**
     * Badge Image Url
     */
    badge_image_url?: string | null;
    /**
     * Featured
     */
    featured?: boolean | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 *
 * Schema for login credentials.
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * PostCreate
 *
 * Schema for creating a new blog post.
 *
 * If a ``slug`` is not provided, one is automatically generated from the
 * ``title`` field.
 */
export type PostCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Excerpt
     */
    excerpt: string;
    /**
     * Body
     */
    body?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Cover Image Url
     */
    cover_image_url?: string | null;
    /**
     * Published
     */
    published?: boolean;
    /**
     * Reading Time Minutes
     */
    reading_time_minutes?: number | null;
    /**
     * Slug
     */
    slug?: string | null;
};

/**
 * PostResponse
 *
 * Schema for returning a blog post in API responses.
 *
 * Includes database-generated fields like ``id``, ``slug``, and timestamps.
 */
export type PostResponse = {
    /**
     * Title
     */
    title: string;
    /**
     * Excerpt
     */
    excerpt: string;
    /**
     * Body
     */
    body?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Cover Image Url
     */
    cover_image_url?: string | null;
    /**
     * Published
     */
    published?: boolean;
    /**
     * Reading Time Minutes
     */
    reading_time_minutes?: number | null;
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PostUpdate
 *
 * Schema for updating an existing blog post.
 *
 * All fields are optional. Only provided fields will be updated.
 */
export type PostUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Excerpt
     */
    excerpt?: string | null;
    /**
     * Body
     */
    body?: string | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Cover Image Url
     */
    cover_image_url?: string | null;
    /**
     * Published
     */
    published?: boolean | null;
    /**
     * Reading Time Minutes
     */
    reading_time_minutes?: number | null;
};

/**
 * ProjectCreate
 *
 * Schema for creating a new project.
 *
 * If a ``slug`` is not provided, one is automatically generated from the
 * ``title`` field.
 */
export type ProjectCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Tech Stack
     */
    tech_stack?: Array<string>;
    /**
     * Live Url
     */
    live_url?: string | null;
    /**
     * Repo Url
     */
    repo_url?: string | null;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Featured
     */
    featured?: boolean;
    /**
     * Published
     */
    published?: boolean;
    /**
     * Order
     */
    order?: number;
    /**
     * Slug
     */
    slug?: string | null;
};

/**
 * ProjectResponse
 *
 * Schema for returning a project in API responses.
 *
 * Includes database-generated fields like ``id``, ``slug``, and timestamps.
 */
export type ProjectResponse = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Tech Stack
     */
    tech_stack?: Array<string>;
    /**
     * Live Url
     */
    live_url?: string | null;
    /**
     * Repo Url
     */
    repo_url?: string | null;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Featured
     */
    featured?: boolean;
    /**
     * Published
     */
    published?: boolean;
    /**
     * Order
     */
    order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectUpdate
 *
 * Schema for updating an existing project.
 *
 * All fields are optional. Only provided fields will be updated.
 */
export type ProjectUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Tech Stack
     */
    tech_stack?: Array<string> | null;
    /**
     * Live Url
     */
    live_url?: string | null;
    /**
     * Repo Url
     */
    repo_url?: string | null;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Featured
     */
    featured?: boolean | null;
    /**
     * Published
     */
    published?: boolean | null;
    /**
     * Order
     */
    order?: number | null;
};

/**
 * TokenResponse
 *
 * Schema for returning a JWT access token.
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserResponse
 *
 * Schema for returning a user profile.
 *
 * The ``hashed_password`` field is deliberately excluded from this schema
 * so it is never accidentally leaked in API responses.
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WriteMode
 */
export type WriteMode = 'write' | 'improve' | 'summarise';

/**
 * WriteRequest
 */
export type WriteRequest = {
    /**
     * Prompt
     */
    prompt: string;
    mode: WriteMode;
    /**
     * Context
     */
    context?: string | null;
};

export type GetProjectsApiV1ProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Published Only
         */
        published_only?: boolean;
    };
    url: '/api/v1/projects/';
};

export type GetProjectsApiV1ProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectsApiV1ProjectsGetError = GetProjectsApiV1ProjectsGetErrors[keyof GetProjectsApiV1ProjectsGetErrors];

export type GetProjectsApiV1ProjectsGetResponses = {
    /**
     * Response Get Projects Api V1 Projects  Get
     *
     * Successful Response
     */
    200: Array<ProjectResponse>;
};

export type GetProjectsApiV1ProjectsGetResponse = GetProjectsApiV1ProjectsGetResponses[keyof GetProjectsApiV1ProjectsGetResponses];

export type CreateProjectApiV1ProjectsPostData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/projects/';
};

export type CreateProjectApiV1ProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectApiV1ProjectsPostError = CreateProjectApiV1ProjectsPostErrors[keyof CreateProjectApiV1ProjectsPostErrors];

export type CreateProjectApiV1ProjectsPostResponses = {
    /**
     * Successful Response
     */
    201: ProjectResponse;
};

export type CreateProjectApiV1ProjectsPostResponse = CreateProjectApiV1ProjectsPostResponses[keyof CreateProjectApiV1ProjectsPostResponses];

export type GetFeaturedProjectsApiV1ProjectsFeaturedGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/projects/featured';
};

export type GetFeaturedProjectsApiV1ProjectsFeaturedGetResponses = {
    /**
     * Response Get Featured Projects Api V1 Projects Featured Get
     *
     * Successful Response
     */
    200: Array<ProjectResponse>;
};

export type GetFeaturedProjectsApiV1ProjectsFeaturedGetResponse = GetFeaturedProjectsApiV1ProjectsFeaturedGetResponses[keyof GetFeaturedProjectsApiV1ProjectsFeaturedGetResponses];

export type DeleteProjectApiV1ProjectsSlugDeleteData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}';
};

export type DeleteProjectApiV1ProjectsSlugDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectApiV1ProjectsSlugDeleteError = DeleteProjectApiV1ProjectsSlugDeleteErrors[keyof DeleteProjectApiV1ProjectsSlugDeleteErrors];

export type DeleteProjectApiV1ProjectsSlugDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectApiV1ProjectsSlugDeleteResponse = DeleteProjectApiV1ProjectsSlugDeleteResponses[keyof DeleteProjectApiV1ProjectsSlugDeleteResponses];

export type GetProjectApiV1ProjectsSlugGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}';
};

export type GetProjectApiV1ProjectsSlugGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectApiV1ProjectsSlugGetError = GetProjectApiV1ProjectsSlugGetErrors[keyof GetProjectApiV1ProjectsSlugGetErrors];

export type GetProjectApiV1ProjectsSlugGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type GetProjectApiV1ProjectsSlugGetResponse = GetProjectApiV1ProjectsSlugGetResponses[keyof GetProjectApiV1ProjectsSlugGetResponses];

export type UpdateProjectApiV1ProjectsSlugPatchData = {
    body: ProjectUpdate;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}';
};

export type UpdateProjectApiV1ProjectsSlugPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectApiV1ProjectsSlugPatchError = UpdateProjectApiV1ProjectsSlugPatchErrors[keyof UpdateProjectApiV1ProjectsSlugPatchErrors];

export type UpdateProjectApiV1ProjectsSlugPatchResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type UpdateProjectApiV1ProjectsSlugPatchResponse = UpdateProjectApiV1ProjectsSlugPatchResponses[keyof UpdateProjectApiV1ProjectsSlugPatchResponses];

export type GetPostsApiV1PostsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Published Only
         */
        published_only?: boolean;
    };
    url: '/api/v1/posts/';
};

export type GetPostsApiV1PostsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostsApiV1PostsGetError = GetPostsApiV1PostsGetErrors[keyof GetPostsApiV1PostsGetErrors];

export type GetPostsApiV1PostsGetResponses = {
    /**
     * Response Get Posts Api V1 Posts  Get
     *
     * Successful Response
     */
    200: Array<PostResponse>;
};

export type GetPostsApiV1PostsGetResponse = GetPostsApiV1PostsGetResponses[keyof GetPostsApiV1PostsGetResponses];

export type CreatePostApiV1PostsPostData = {
    body: PostCreate;
    path?: never;
    query?: never;
    url: '/api/v1/posts/';
};

export type CreatePostApiV1PostsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePostApiV1PostsPostError = CreatePostApiV1PostsPostErrors[keyof CreatePostApiV1PostsPostErrors];

export type CreatePostApiV1PostsPostResponses = {
    /**
     * Successful Response
     */
    201: PostResponse;
};

export type CreatePostApiV1PostsPostResponse = CreatePostApiV1PostsPostResponses[keyof CreatePostApiV1PostsPostResponses];

export type DeletePostApiV1PostsSlugDeleteData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/posts/{slug}';
};

export type DeletePostApiV1PostsSlugDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePostApiV1PostsSlugDeleteError = DeletePostApiV1PostsSlugDeleteErrors[keyof DeletePostApiV1PostsSlugDeleteErrors];

export type DeletePostApiV1PostsSlugDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePostApiV1PostsSlugDeleteResponse = DeletePostApiV1PostsSlugDeleteResponses[keyof DeletePostApiV1PostsSlugDeleteResponses];

export type GetPostApiV1PostsSlugGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/posts/{slug}';
};

export type GetPostApiV1PostsSlugGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostApiV1PostsSlugGetError = GetPostApiV1PostsSlugGetErrors[keyof GetPostApiV1PostsSlugGetErrors];

export type GetPostApiV1PostsSlugGetResponses = {
    /**
     * Successful Response
     */
    200: PostResponse;
};

export type GetPostApiV1PostsSlugGetResponse = GetPostApiV1PostsSlugGetResponses[keyof GetPostApiV1PostsSlugGetResponses];

export type UpdatePostApiV1PostsSlugPatchData = {
    body: PostUpdate;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/posts/{slug}';
};

export type UpdatePostApiV1PostsSlugPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePostApiV1PostsSlugPatchError = UpdatePostApiV1PostsSlugPatchErrors[keyof UpdatePostApiV1PostsSlugPatchErrors];

export type UpdatePostApiV1PostsSlugPatchResponses = {
    /**
     * Successful Response
     */
    200: PostResponse;
};

export type UpdatePostApiV1PostsSlugPatchResponse = UpdatePostApiV1PostsSlugPatchResponses[keyof UpdatePostApiV1PostsSlugPatchResponses];

export type GetCertificationsApiV1CertificationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Featured Only
         */
        featured_only?: boolean;
    };
    url: '/api/v1/certifications/';
};

export type GetCertificationsApiV1CertificationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCertificationsApiV1CertificationsGetError = GetCertificationsApiV1CertificationsGetErrors[keyof GetCertificationsApiV1CertificationsGetErrors];

export type GetCertificationsApiV1CertificationsGetResponses = {
    /**
     * Response Get Certifications Api V1 Certifications  Get
     *
     * Successful Response
     */
    200: Array<CertificationResponse>;
};

export type GetCertificationsApiV1CertificationsGetResponse = GetCertificationsApiV1CertificationsGetResponses[keyof GetCertificationsApiV1CertificationsGetResponses];

export type CreateCertificationApiV1CertificationsPostData = {
    body: CertificationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/certifications/';
};

export type CreateCertificationApiV1CertificationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCertificationApiV1CertificationsPostError = CreateCertificationApiV1CertificationsPostErrors[keyof CreateCertificationApiV1CertificationsPostErrors];

export type CreateCertificationApiV1CertificationsPostResponses = {
    /**
     * Successful Response
     */
    201: CertificationResponse;
};

export type CreateCertificationApiV1CertificationsPostResponse = CreateCertificationApiV1CertificationsPostResponses[keyof CreateCertificationApiV1CertificationsPostResponses];

export type DeleteCertificationApiV1CertificationsCertIdDeleteData = {
    body?: never;
    path: {
        /**
         * Cert Id
         */
        cert_id: string;
    };
    query?: never;
    url: '/api/v1/certifications/{cert_id}';
};

export type DeleteCertificationApiV1CertificationsCertIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCertificationApiV1CertificationsCertIdDeleteError = DeleteCertificationApiV1CertificationsCertIdDeleteErrors[keyof DeleteCertificationApiV1CertificationsCertIdDeleteErrors];

export type DeleteCertificationApiV1CertificationsCertIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCertificationApiV1CertificationsCertIdDeleteResponse = DeleteCertificationApiV1CertificationsCertIdDeleteResponses[keyof DeleteCertificationApiV1CertificationsCertIdDeleteResponses];

export type GetCertificationApiV1CertificationsCertIdGetData = {
    body?: never;
    path: {
        /**
         * Cert Id
         */
        cert_id: string;
    };
    query?: never;
    url: '/api/v1/certifications/{cert_id}';
};

export type GetCertificationApiV1CertificationsCertIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCertificationApiV1CertificationsCertIdGetError = GetCertificationApiV1CertificationsCertIdGetErrors[keyof GetCertificationApiV1CertificationsCertIdGetErrors];

export type GetCertificationApiV1CertificationsCertIdGetResponses = {
    /**
     * Successful Response
     */
    200: CertificationResponse;
};

export type GetCertificationApiV1CertificationsCertIdGetResponse = GetCertificationApiV1CertificationsCertIdGetResponses[keyof GetCertificationApiV1CertificationsCertIdGetResponses];

export type UpdateCertificationApiV1CertificationsCertIdPatchData = {
    body: CertificationUpdate;
    path: {
        /**
         * Cert Id
         */
        cert_id: string;
    };
    query?: never;
    url: '/api/v1/certifications/{cert_id}';
};

export type UpdateCertificationApiV1CertificationsCertIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCertificationApiV1CertificationsCertIdPatchError = UpdateCertificationApiV1CertificationsCertIdPatchErrors[keyof UpdateCertificationApiV1CertificationsCertIdPatchErrors];

export type UpdateCertificationApiV1CertificationsCertIdPatchResponses = {
    /**
     * Successful Response
     */
    200: CertificationResponse;
};

export type UpdateCertificationApiV1CertificationsCertIdPatchResponse = UpdateCertificationApiV1CertificationsCertIdPatchResponses[keyof UpdateCertificationApiV1CertificationsCertIdPatchResponses];

export type AiWriteApiV1AiWritePostData = {
    body: WriteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/write';
};

export type AiWriteApiV1AiWritePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiWriteApiV1AiWritePostError = AiWriteApiV1AiWritePostErrors[keyof AiWriteApiV1AiWritePostErrors];

export type AiWriteApiV1AiWritePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginApiV1AuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type MeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type MeApiV1AuthMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeApiV1AuthMeGetError = MeApiV1AuthMeGetErrors[keyof MeApiV1AuthMeGetErrors];

export type MeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type MeApiV1AuthMeGetResponse = MeApiV1AuthMeGetResponses[keyof MeApiV1AuthMeGetResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutApiV1AuthLogoutPostError = LogoutApiV1AuthLogoutPostErrors[keyof LogoutApiV1AuthLogoutPostErrors];

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiV1AuthLogoutPostResponse = LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];
