"""'initial schema'

Revision ID: a0390250674e
Revises:
Create Date: 2026-02-17 23:12:17.149027

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a0390250674e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
