"""Resize content_embedding columns from vector(1536) to vector(768).

Switches the embedding backend from OpenAI text-embedding-3-small (1 536 dims)
to a locally-hosted BAAI/bge-base-en-v1.5 model served by infinity-emb
(768 dims).

pgvector does not support ALTER COLUMN for vector types — the column must be
dropped and re-created.  Because the old embeddings were generated by a
cloud model that is no longer used, all existing embedding data is intentionally
discarded; every row will have content_embedding = NULL after this migration
and must be re-indexed via the "Re-embed" action in the admin CMS.

Revision ID: d3456789012c
Revises: c2345678901b
Create Date: 2025-01-01 00:00:00.000000
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3456789012c"
down_revision: str | None = "c2345678901b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Tables that carry a content_embedding vector column.
_TABLES = ("projects", "posts", "certifications")

_OLD_DIMS = 1536  # text-embedding-3-small
_NEW_DIMS = 768  # BAAI/bge-base-en-v1.5


def upgrade() -> None:
    """Drop vector(1536) columns and re-create them as vector(768).

    Existing embedding data is dropped — rows will have NULL embeddings
    until re-indexed.  The pgvector extension must already be installed
    (it is created in the initial migration).
    """
    for table in _TABLES:
        # DROP the old column — pgvector cannot ALTER the dimension in place.
        op.execute(f"ALTER TABLE {table} DROP COLUMN IF EXISTS content_embedding")

        # Re-create with the new dimension.
        op.execute(f"ALTER TABLE {table} ADD COLUMN content_embedding vector({_NEW_DIMS})")


def downgrade() -> None:
    """Revert to vector(1536) columns (drops all current embedding data)."""
    for table in _TABLES:
        op.execute(f"ALTER TABLE {table} DROP COLUMN IF EXISTS content_embedding")
        op.execute(f"ALTER TABLE {table} ADD COLUMN content_embedding vector({_OLD_DIMS})")
